# Generated by Django 4.0.5 on 2022-07-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
